name: Deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Paso b√°sico de CI
      run: echo "CI funcionando"

    - name: Show secret in build (demo)
      run: |
          echo "El secret de GitHub es: $MY_SECRET_MESSAGE"
      env:
        MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
